"""Add ticket_transfer table

Revision ID: 99f6ea7df7cd
Revises: d36b92f786bd
Create Date: 2026-02-12 22:40:19.025600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f6ea7df7cd'
down_revision = 'd36b92f786bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_transfer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_item_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('transfer_token', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_item_id'], ['booking_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_user_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_token')
    )
    op.create_index('ix_ticket_transfer_from', 'ticket_transfer', ['from_user_id'], unique=False)
    op.create_index('ix_ticket_transfer_item', 'ticket_transfer', ['booking_item_id'], unique=False)
    op.create_index('ix_ticket_transfer_status', 'ticket_transfer', ['status'], unique=False)
    op.create_index('ix_ticket_transfer_to', 'ticket_transfer', ['to_user_id'], unique=False)
    op.create_index('ix_ticket_transfer_token', 'ticket_transfer', ['transfer_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_transfer_token', table_name='ticket_transfer')
    op.drop_index('ix_ticket_transfer_to', table_name='ticket_transfer')
    op.drop_index('ix_ticket_transfer_status', table_name='ticket_transfer')
    op.drop_index('ix_ticket_transfer_item', table_name='ticket_transfer')
    op.drop_index('ix_ticket_transfer_from', table_name='ticket_transfer')
    op.drop_table('ticket_transfer')
    # ### end Alembic commands ###
