"""add_notification_preference_table

Revision ID: 80d512d7a93e
Revises: 99f6ea7df7cd
Create Date: 2026-02-12 22:57:28.906450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d512d7a93e'
down_revision = '99f6ea7df7cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_booking_confirmation', sa.Boolean(), nullable=False),
    sa.Column('email_payment_updates', sa.Boolean(), nullable=False),
    sa.Column('email_ticket_delivery', sa.Boolean(), nullable=False),
    sa.Column('email_event_reminders', sa.Boolean(), nullable=False),
    sa.Column('email_event_updates', sa.Boolean(), nullable=False),
    sa.Column('email_transfer_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_marketing', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_preference')
    # ### end Alembic commands ###
