"""Add payment table

Revision ID: d36b92f786bd
Revises: phase2_event_venue
Create Date: 2026-02-12 22:34:39.730394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36b92f786bd'
down_revision = 'phase2_event_venue'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_purchase', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_promo_code_code', 'promo_code', ['code'], unique=False)
    op.create_index('ix_promo_code_event', 'promo_code', ['event_id'], unique=False)
    op.create_table('booking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('payment_id', sa.String(length=255), nullable=True),
    sa.Column('promo_code_id', sa.Integer(), nullable=True),
    sa.Column('promo_code_used', sa.String(length=50), nullable=True),
    sa.Column('ticket_count', sa.Integer(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_code.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_number')
    )
    op.create_index('ix_booking_event', 'booking', ['event_id'], unique=False)
    op.create_index('ix_booking_number', 'booking', ['booking_number'], unique=False)
    op.create_index('ix_booking_status', 'booking', ['status'], unique=False)
    op.create_index('ix_booking_user', 'booking', ['user_id'], unique=False)
    op.create_table('cart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_code.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cart_expires', 'cart', ['expires_at'], unique=False)
    op.create_index('ix_cart_status', 'cart', ['status'], unique=False)
    op.create_index('ix_cart_user_event', 'cart', ['user_id', 'event_id'], unique=False)
    op.create_table('booking_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('seat_label', sa.String(length=50), nullable=True),
    sa.Column('ticket_number', sa.String(length=50), nullable=False),
    sa.Column('qr_code_data', sa.String(length=500), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['seat_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['seat.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number')
    )
    op.create_index('ix_booking_item_booking', 'booking_item', ['booking_id'], unique=False)
    op.create_index('ix_booking_item_ticket', 'booking_item', ['ticket_number'], unique=False)
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('seat_category_id', sa.Integer(), nullable=False),
    sa.Column('seat_ids', sa.JSON(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_category_id'], ['seat_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cart_item_cart', 'cart_item', ['cart_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_description', sa.String(length=500), nullable=True),
    sa.Column('refund_id', sa.String(length=100), nullable=True),
    sa.Column('refund_amount', sa.Integer(), nullable=True),
    sa.Column('refund_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id')
    )
    op.create_index('ix_payment_booking', 'payment', ['booking_id'], unique=False)
    op.create_index('ix_payment_order_id', 'payment', ['razorpay_order_id'], unique=False)
    op.create_index('ix_payment_status', 'payment', ['status'], unique=False)
    op.create_index('ix_payment_user', 'payment', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_user', table_name='payment')
    op.drop_index('ix_payment_status', table_name='payment')
    op.drop_index('ix_payment_order_id', table_name='payment')
    op.drop_index('ix_payment_booking', table_name='payment')
    op.drop_table('payment')
    op.drop_index('ix_cart_item_cart', table_name='cart_item')
    op.drop_table('cart_item')
    op.drop_index('ix_booking_item_ticket', table_name='booking_item')
    op.drop_index('ix_booking_item_booking', table_name='booking_item')
    op.drop_table('booking_item')
    op.drop_index('ix_cart_user_event', table_name='cart')
    op.drop_index('ix_cart_status', table_name='cart')
    op.drop_index('ix_cart_expires', table_name='cart')
    op.drop_table('cart')
    op.drop_index('ix_booking_user', table_name='booking')
    op.drop_index('ix_booking_status', table_name='booking')
    op.drop_index('ix_booking_number', table_name='booking')
    op.drop_index('ix_booking_event', table_name='booking')
    op.drop_table('booking')
    op.drop_index('ix_promo_code_event', table_name='promo_code')
    op.drop_index('ix_promo_code_code', table_name='promo_code')
    op.drop_table('promo_code')
    op.drop_table('user_device')
    # ### end Alembic commands ###
